### ISSUE TITLE
Continuo implementazione view-control

### ISSUE THREAD

**Issue by FakeDaemon** [ranghetto/Qovid#31]
- [x] inplementazione getter/setter di raggio d'infezione 
- [x] inplementazione getter/setter di prob di morte
- [x] inplementazione getter/setter di prob contagio
- [x] modifica valori del costruttore di world (lascio per valore, non li salvo come parametri)

**Comment by FakeDaemon** [comment]
- [x] implementare come impostabile il tempo in cui un entità si trova nello stato INFECTED

**Comment by FakeDaemon** [comment]
1. I parametri del costruttore di Actor sono float e le QSpinBoat ritornano un valore int
2. Nell'interfaccia richiedo la death_rate, nel costruttore di Actor c'è al suo posto il campo surviveRateo, dobbiamo sistemare 
@ranghetto

**Comment by ranghetto** [comment]
> 1. I parametri del costruttore di Actor sono float e le QSpinBoat ritornano un valore int
> 
>     2. Nell'interfaccia richiedo la death_rate, nel costruttore di Actor c'è al suo posto il campo surviveRateo, dobbiamo sistemare
>        @ranghetto

1. valori ora sono `uint` #33
2. era rimasto un refuso, il termine giusto e' `deathRate`, lo metto sempre nella issue #33

**Comment by ranghetto** [comment]
- [x] Aggiungere campo `Infetti Iniziali` (da trovare un nome migliore ma il senso e' quello) che come massimo valore ha quello di popolazione

Per farlo basta collegare il signal `valueChanged` della spinbox ad uno slot in cui si chiama la funzione che setta il massimo valore della spinbox
