### ISSUE TITLE
Container popolazione

### ISSUE THREAD

**Issue by ranghetto** [ranghetto/Qovid#4]
1. Implementare un modello container per la popolazione
2. Implementare una funzionalià nel ~~controller della simulazione~~ modello Popolazione che permetta di risalire ad una lista di persone in un certo raggio `r` ~~dato un punto `(x,y)`~~ data la posizione di una persona. Deve ritornare tutte le persone tranne quella passata.

**Comment by ranghetto** [comment]
- [x] Inizializzazione della popolazione
- [ ] Funzione per la ricerca descritta sopra

**Comment by ranghetto** [comment]
- [x] refactor del metodo `doAction` in `PersonModel` e delle Action
Il costruttore di una "Action" non dovrebbe richiedere un PersonModel, perche' intuitavamente quando vado a creare un'azione non so chi la eseguira', sara' il metodo `doAction()` a passare la persona stessa all' `operator()` delle classi derivate da `ActionAbstractModel`

* pensavo a questo punto di creare un controller per le azioni

@FakeDaemon give me feedback pls

**Comment by FakeDaemon** [comment]
> * [ ]  refactor del metodo `doAction` in `PersonModel` e delle Action
>   Il costruttore di una "Action" non dovrebbe richiedere un PersonModel, perche' intuitavamente quando vado a creare un'azione non so chi la eseguira', sara' il metodo `doAction()` a passare la persona stessa all' `operator()` delle classi derivate da `ActionAbstractModel`
> 
> * pensavo a questo punto di creare un controller per le azioni
> 
> @FakeDaemon give me feedback pls

Va bene, in realtà visto che la simulazione è la parte un po più delicata del programma potremmo dedicarle un controller specifico, e lasciare l'altro a gestire la view.
